### ISSUE TITLE
porting recipes to conda-forge

### ISSUE THREAD

**Issue by grlee77** [gadgetron/gadgetron-conda-recipes#1]
Is there any interest from the gadgetron devs in collaborating to make some or all of these packages available through `conda-forge` (http://conda-forge.github.io/)?  The main benefit provided would be the use of continuous integration to verify package builds for each platform.  Also, you will likely be able to get additional maintainers on some of the recipes that are of broader interest to the community (e.g. the link in the armadillo recipe here currently seems to be expired).

I can help start the conversions if you are interested.  `fftw` is already on conda-forge, but I think the rest would be new.  I have found the developers there to be very responsive and helpful with recipes I have submitted in the past.

**Comment by congzhangzh** [comment]
a good idea:)

**Comment by congzhangzh** [comment]
@inati I am interesting to maintain gadgetron recipes, but I mainly focus on Windows and Linux
@grlee77  seems @inati does not do gadgetron related works anymore:)

**Comment by grlee77** [comment]
Hi @congzhangzh. If you are interested in pursuing this I would check in with @dchansen and @xueh2 who have been more active recently in Gadgetron development. I am not sure what the level of interest is on their end.

One difficulty with conda-forge and Gadgetron is the lack of CUDA/GPU support on the free CI services that test the recipes, so I think it would have to be a CPU-only build. Also, I haven't tried building Gadgetron recently, so I am not sure if it is compatible with the current default compilers and library versions at conda-forge. They are probably more recent than whatever comes with Ubuntu 16.04 or 18.04 by default and it might require some patches to Gadgetron itself to get everything working. I think conda-forge has started to move to quite recent compiler versions in common with the Anaconda default channels (e.g. GCC 7, etc). I am also not sure what C++ language standard is most common for C++-based recipes (C++11?) as I mainly work in Python.

I don't currently have much bandwidth to work on recipes, but I would be happy to help take a look at any you may come up with. 

A number of the ISMRMRD/Gadgetron dependencies (CMake, Boost, FFTW, HDF5) are already on conda-forge:
https://github.com/conda-forge/fftw-feedstock
https://github.com/conda-forge/hdf5-feedstock
https://github.com/conda-forge/cmake-feedstock
https://github.com/conda-forge/boost-feedstock

and I contributed a couple of others some time back:
https://github.com/conda-forge/armadillo-feedstock
https://github.com/conda-forge/pyxb-feedstock

At one point, I made a PR for ACE, but never finalized getting it merged, so it is probably out of date (and I think there are plans to eventually remove the ACE dependency from Gadgetron?):
https://github.com/conda-forge/staged-recipes/pull/2410

**Comment by xueh2** [comment]
Hi @congzhangzh. I am not against this idea. It will make the cpu version of gadgetron easier to install. Currently we do maintain docker images for gadgetron. This is a way people can get jump started. But if you want to give a go with conda, i am supportive and can help testing if you need. 

Latest gadgetron requires c++ 11 or above and had a few dependencies, including ACE. I suppose getting all dependencies may be the major barrier.

But if you move ahead, keep us posted.

**Comment by congzhangzh** [comment]
@grlee77 ACE is monster,  but I do not think Gadgetron will remove the ACE dependency, although some code is already using boost.asio, it's very few. ACE api is really very elegent and powerful:)

**Comment by congzhangzh** [comment]
Hi @xueh2,  tks for advice and support from  Gadgetron  official developer first

Cmake is pretty awesome,  but the platform like windows is really lack of good ability to manager package and libraries like what done by Debian or others. 

Vcpkg and Conda is awesome, and first I try to make Gadgetron work with vcpkg(it works for 3.8.2 and the process is very easy when follow https://vcpkg.readthedocs.io/en/latest/users/integration/ ), and I even push ismrmrd to vcpkg https://github.com/Microsoft/vcpkg/issues/2945

But vcpkg is more like a libraries manager but not distrubution https://github.com/Microsoft/vcpkg/issues/4292 , it's not a good idea to distrubution gadgetron on it.

So I try to make this on conda possible:)

**Comment by congzhangzh** [comment]
@xueh2 @hansenms 

BTW, when I try to build gadgetron on windows 10 with vcpkg library(it works),  https://github.com/medlab/gadgetron/commits/win10-64

one change I am not sure is omp related, the change is bad and break developer's expect, but I can not find a workaround.

https://github.com/medlab/gadgetron/commit/65f3f09a63e9d797a78aef62fa3ff72ea1feb14d

would you mind to do do a code review?

and for another changeset may be usefull for gadgetron https://github.com/medlab/gadgetron/commit/897c1c92ba09834fd06a185dd223983805e022ed ,

is that possibleto upstream or partial upstream these change first?

**Comment by dchansen** [comment]
Hi @congzhangzh,
We've just recently gotten Gadgetron to build with vcpkg - they will become part of Gadgetron when we've gotten the automatic test system up and running with them.

I am a little surprised that you need the omp changes, as the tests all pass here without those changes. 

As for ACE... well, getting rid of it is certainly on our todo list, but it is also a massive undertaking, so don't expect it to go anywhere soon.

**Comment by congzhangzh** [comment]
@dchansen tks for you reply， which Visual Studio version you used? I use Visual Studio 2017 Community Version.

**Comment by hansenms** [comment]
I am closing this, since it is some years old. We have a PR up (#2) to rework how these conda packages are generated. These new packages enable install with GPU support.
